# Generated by Django 6.0.4 on 2026-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalTitle', models.CharField(max_length=100)),
                ('goalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currentAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goalDeadline', models.DateField()),
            ],
        ),
    ]
