# Generated by Django 6.0.4 on 2026-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goalCategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='goalDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goalPriority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
