# Generated by Django 6.0.4 on 2026-04-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goalcategory_goal_goaldescription_and_more'),
    ]

    operations = [
    ]
