# Generated by Django 6.0.4 on 2026-04-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20260429_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goalCategory',
        ),
    ]
