# Generated by Django 6.0.4 on 2026-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Category', models.CharField(max_length=200)),
                ('Payment_Method', models.CharField(verbose_name=100)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Source', models.CharField(max_length=200)),
                ('Payment_Method', models.CharField(max_length=100)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Date', models.DateField()),
                ('Recurring_income', models.BooleanField(default=False)),
            ],
        ),
    ]
