# Generated by Django 6.0.4 on 2026-04-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_expenses_amount_alter_expenses_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='Notes',
        ),
    ]
